# -*- coding: utf-8 -*-
"""6410545444_dogs_cats.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zVp46npnyFL4DObNiJzTdPJUlP_JtmOp

## Gradio Pets
"""
from fastai.vision.all import *
from pathlib import Path
import gradio as gr

def is_cat(x): return x[0].isupper()

img = PILImage.create('cat.webp')

img.thumbnail((128,128))
img

learn = load_learner('model.pkl')

learn.predict(img)

learn.export('model.pkl')

# Define a function for model inference
def classify_image(inp):
    img = PILImage.create(inp)
    img.thumbnail((128,128))
    pred,pred_idx,probs = learn.predict(img)
    return (
        f"The image is a Dog with probability {probs[pred_idx]:.4f}"
        if pred == "class_A"
        else f"The image is look like a Cat {probs[pred_idx]:.4f}"
    )

image = gr.Image()
label = gr.Label()
examples = ["cat.webp", "dog.webp", "bear.jpeg"]

# Create a Gradio interface
gr.Interface(fn=classify_image, inputs="image", outputs="text", examples=examples).launch()